version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_HOST: "localhost"
      DB_PORT: "5433"
      DB_USER: "oleglisavalov"
      DB_PASSWORD: "123123"
      DB_NAME: "db_for_task"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: db_for_task
    restart: always
    environment:
      POSTGRES_USER: "oleglisavalov"
      POSTGRES_PASSWORD: "123123"
      POSTGRES_DB: "db_for_task"
    ports:
      - "5433:5433"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
